"""added course title

Revision ID: 80270693e16d
Revises: d6325c2cfb5b
Create Date: 2023-06-24 21:27:12.474845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80270693e16d'
down_revision = 'd6325c2cfb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=255), nullable=False,server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('course_title')

    # ### end Alembic commands ###
