"""home pic

Revision ID: b4579a5c50c1
Revises: 515a09281696
Create Date: 2023-08-01 15:45:31.089773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4579a5c50c1'
down_revision = '515a09281696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_image',
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.Column('home_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('home_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_image')
    # ### end Alembic commands ###
